import Navbar from "../components/Header/Navbar";
import Head from "next/head";
import Main from "../components/Body/Main";
import About from "../components/Body/About";
import Projects from "../components/Body/Projects";
import Image from "next/image";
import Skills from "../components/Body/Skills";
import Contact from "../components/Body/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Harmon Rod | Front-End Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Contact />
    </div>
  );
}
